//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 12:54:15 AM BRT 
//


package br.inf.portalfiscal.cte;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nMinu" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;whiteSpace value="preserve"/>
 *               &lt;pattern value="[0-9]{9}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nOCA" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;whiteSpace value="preserve"/>
 *               &lt;pattern value="[0-9]{11}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="dPrevAereo" type="{http://www.portalfiscal.inf.br/cte}TData"/>
 *         &lt;element name="xLAgEmi" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
 *               &lt;maxLength value="20"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IdT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
 *               &lt;maxLength value="14"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tarifa">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CL">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="1"/>
 *                         &lt;whiteSpace value="preserve"/>
 *                         &lt;pattern value="M"/>
 *                         &lt;pattern value="G"/>
 *                         &lt;pattern value="E"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="cTar" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="4"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="vTar" type="{http://www.portalfiscal.inf.br/cte}TDec_1302"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="natCarga">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="xDime" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
 *                         &lt;minLength value="5"/>
 *                         &lt;maxLength value="14"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="cInfManu" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;whiteSpace value="preserve"/>
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="3"/>
 *                         &lt;enumeration value="4"/>
 *                         &lt;enumeration value="5"/>
 *                         &lt;enumeration value="6"/>
 *                         &lt;enumeration value="7"/>
 *                         &lt;enumeration value="8"/>
 *                         &lt;enumeration value="9"/>
 *                         &lt;enumeration value="99"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="cIMP" maxOccurs="unbounded">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
 *                         &lt;minLength value="3"/>
 *                         &lt;maxLength value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nMinu",
    "noca",
    "dPrevAereo",
    "xlAgEmi",
    "idT",
    "tarifa",
    "natCarga"
})
@XmlRootElement(name = "aereo")
public class Aereo {

    protected String nMinu;
    @XmlElement(name = "nOCA")
    protected String noca;
    @XmlElement(required = true)
    protected String dPrevAereo;
    @XmlElement(name = "xLAgEmi")
    protected String xlAgEmi;
    @XmlElement(name = "IdT")
    protected String idT;
    @XmlElement(required = true)
    protected Aereo.Tarifa tarifa;
    @XmlElement(required = true)
    protected Aereo.NatCarga natCarga;

    /**
     * Gets the value of the nMinu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNMinu() {
        return nMinu;
    }

    /**
     * Sets the value of the nMinu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNMinu(String value) {
        this.nMinu = value;
    }

    /**
     * Gets the value of the noca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOCA() {
        return noca;
    }

    /**
     * Sets the value of the noca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOCA(String value) {
        this.noca = value;
    }

    /**
     * Gets the value of the dPrevAereo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDPrevAereo() {
        return dPrevAereo;
    }

    /**
     * Sets the value of the dPrevAereo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDPrevAereo(String value) {
        this.dPrevAereo = value;
    }

    /**
     * Gets the value of the xlAgEmi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXLAgEmi() {
        return xlAgEmi;
    }

    /**
     * Sets the value of the xlAgEmi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXLAgEmi(String value) {
        this.xlAgEmi = value;
    }

    /**
     * Gets the value of the idT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdT() {
        return idT;
    }

    /**
     * Sets the value of the idT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdT(String value) {
        this.idT = value;
    }

    /**
     * Gets the value of the tarifa property.
     * 
     * @return
     *     possible object is
     *     {@link Aereo.Tarifa }
     *     
     */
    public Aereo.Tarifa getTarifa() {
        return tarifa;
    }

    /**
     * Sets the value of the tarifa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aereo.Tarifa }
     *     
     */
    public void setTarifa(Aereo.Tarifa value) {
        this.tarifa = value;
    }

    /**
     * Gets the value of the natCarga property.
     * 
     * @return
     *     possible object is
     *     {@link Aereo.NatCarga }
     *     
     */
    public Aereo.NatCarga getNatCarga() {
        return natCarga;
    }

    /**
     * Sets the value of the natCarga property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aereo.NatCarga }
     *     
     */
    public void setNatCarga(Aereo.NatCarga value) {
        this.natCarga = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="xDime" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
     *               &lt;minLength value="5"/>
     *               &lt;maxLength value="14"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="cInfManu" maxOccurs="unbounded" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;whiteSpace value="preserve"/>
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="3"/>
     *               &lt;enumeration value="4"/>
     *               &lt;enumeration value="5"/>
     *               &lt;enumeration value="6"/>
     *               &lt;enumeration value="7"/>
     *               &lt;enumeration value="8"/>
     *               &lt;enumeration value="9"/>
     *               &lt;enumeration value="99"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="cIMP" maxOccurs="unbounded">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
     *               &lt;minLength value="3"/>
     *               &lt;maxLength value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "xDime",
        "cInfManu",
        "cimp"
    })
    public static class NatCarga {

        protected String xDime;
        protected List<String> cInfManu;
        @XmlElement(name = "cIMP", required = true)
        protected List<String> cimp;

        /**
         * Gets the value of the xDime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXDime() {
            return xDime;
        }

        /**
         * Sets the value of the xDime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXDime(String value) {
            this.xDime = value;
        }

        /**
         * Gets the value of the cInfManu property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cInfManu property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCInfManu().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCInfManu() {
            if (cInfManu == null) {
                cInfManu = new ArrayList<String>();
            }
            return this.cInfManu;
        }

        /**
         * Gets the value of the cimp property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the cimp property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCIMP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCIMP() {
            if (cimp == null) {
                cimp = new ArrayList<String>();
            }
            return this.cimp;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CL">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="1"/>
     *               &lt;whiteSpace value="preserve"/>
     *               &lt;pattern value="M"/>
     *               &lt;pattern value="G"/>
     *               &lt;pattern value="E"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="cTar" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="vTar" type="{http://www.portalfiscal.inf.br/cte}TDec_1302"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cl",
        "cTar",
        "vTar"
    })
    public static class Tarifa {

        @XmlElement(name = "CL", required = true)
        protected String cl;
        protected String cTar;
        @XmlElement(required = true)
        protected String vTar;

        /**
         * Gets the value of the cl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCL() {
            return cl;
        }

        /**
         * Sets the value of the cl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCL(String value) {
            this.cl = value;
        }

        /**
         * Gets the value of the cTar property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCTar() {
            return cTar;
        }

        /**
         * Sets the value of the cTar property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCTar(String value) {
            this.cTar = value;
        }

        /**
         * Gets the value of the vTar property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVTar() {
            return vTar;
        }

        /**
         * Sets the value of the vTar property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVTar(String value) {
            this.vTar = value;
        }

    }

}
