//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.26 at 12:54:15 AM BRT 
//


package br.inf.portalfiscal.cte;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tpTraf">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;whiteSpace value="preserve"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="trafMut" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="respFat">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;whiteSpace value="preserve"/>
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ferrEmi">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;whiteSpace value="preserve"/>
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fluxo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="idTrem" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="7"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="vFrete" type="{http://www.portalfiscal.inf.br/cte}TDec_1302"/>
 *         &lt;element name="ferroEnv" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CNPJ" type="{http://www.portalfiscal.inf.br/cte}TCnpj"/>
 *                   &lt;element name="cInt" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="10"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="IE" type="{http://www.portalfiscal.inf.br/cte}TIe" minOccurs="0"/>
 *                   &lt;element name="xNome">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
 *                         &lt;maxLength value="60"/>
 *                         &lt;minLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="enderFerro" type="{http://www.portalfiscal.inf.br/cte}TEnderFer"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="detVag" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nVag">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;whiteSpace value="preserve"/>
 *                         &lt;pattern value="[0-9]{8}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="cap" type="{http://www.portalfiscal.inf.br/cte}TDec_0303" minOccurs="0"/>
 *                   &lt;element name="tpVag" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
 *                         &lt;length value="3"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="pesoR" type="{http://www.portalfiscal.inf.br/cte}TDec_0303"/>
 *                   &lt;element name="pesoBC" type="{http://www.portalfiscal.inf.br/cte}TDec_0303"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tpTraf",
    "trafMut",
    "fluxo",
    "idTrem",
    "vFrete",
    "ferroEnv",
    "detVag"
})
@XmlRootElement(name = "ferrov")
public class Ferrov {

    @XmlElement(required = true)
    protected String tpTraf;
    protected Ferrov.TrafMut trafMut;
    @XmlElement(required = true)
    protected String fluxo;
    protected String idTrem;
    @XmlElement(required = true)
    protected String vFrete;
    protected List<Ferrov.FerroEnv> ferroEnv;
    @XmlElement(required = true)
    protected List<Ferrov.DetVag> detVag;

    /**
     * Gets the value of the tpTraf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTpTraf() {
        return tpTraf;
    }

    /**
     * Sets the value of the tpTraf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTpTraf(String value) {
        this.tpTraf = value;
    }

    /**
     * Gets the value of the trafMut property.
     * 
     * @return
     *     possible object is
     *     {@link Ferrov.TrafMut }
     *     
     */
    public Ferrov.TrafMut getTrafMut() {
        return trafMut;
    }

    /**
     * Sets the value of the trafMut property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ferrov.TrafMut }
     *     
     */
    public void setTrafMut(Ferrov.TrafMut value) {
        this.trafMut = value;
    }

    /**
     * Gets the value of the fluxo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFluxo() {
        return fluxo;
    }

    /**
     * Sets the value of the fluxo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFluxo(String value) {
        this.fluxo = value;
    }

    /**
     * Gets the value of the idTrem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdTrem() {
        return idTrem;
    }

    /**
     * Sets the value of the idTrem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdTrem(String value) {
        this.idTrem = value;
    }

    /**
     * Gets the value of the vFrete property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVFrete() {
        return vFrete;
    }

    /**
     * Sets the value of the vFrete property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVFrete(String value) {
        this.vFrete = value;
    }

    /**
     * Gets the value of the ferroEnv property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ferroEnv property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFerroEnv().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ferrov.FerroEnv }
     * 
     * 
     */
    public List<Ferrov.FerroEnv> getFerroEnv() {
        if (ferroEnv == null) {
            ferroEnv = new ArrayList<Ferrov.FerroEnv>();
        }
        return this.ferroEnv;
    }

    /**
     * Gets the value of the detVag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detVag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetVag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ferrov.DetVag }
     * 
     * 
     */
    public List<Ferrov.DetVag> getDetVag() {
        if (detVag == null) {
            detVag = new ArrayList<Ferrov.DetVag>();
        }
        return this.detVag;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nVag">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;whiteSpace value="preserve"/>
     *               &lt;pattern value="[0-9]{8}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="cap" type="{http://www.portalfiscal.inf.br/cte}TDec_0303" minOccurs="0"/>
     *         &lt;element name="tpVag" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
     *               &lt;length value="3"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="pesoR" type="{http://www.portalfiscal.inf.br/cte}TDec_0303"/>
     *         &lt;element name="pesoBC" type="{http://www.portalfiscal.inf.br/cte}TDec_0303"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nVag",
        "cap",
        "tpVag",
        "pesoR",
        "pesoBC"
    })
    public static class DetVag {

        @XmlElement(required = true)
        protected String nVag;
        protected String cap;
        protected String tpVag;
        @XmlElement(required = true)
        protected String pesoR;
        @XmlElement(required = true)
        protected String pesoBC;

        /**
         * Gets the value of the nVag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNVag() {
            return nVag;
        }

        /**
         * Sets the value of the nVag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNVag(String value) {
            this.nVag = value;
        }

        /**
         * Gets the value of the cap property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCap() {
            return cap;
        }

        /**
         * Sets the value of the cap property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCap(String value) {
            this.cap = value;
        }

        /**
         * Gets the value of the tpVag property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTpVag() {
            return tpVag;
        }

        /**
         * Sets the value of the tpVag property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTpVag(String value) {
            this.tpVag = value;
        }

        /**
         * Gets the value of the pesoR property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPesoR() {
            return pesoR;
        }

        /**
         * Sets the value of the pesoR property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPesoR(String value) {
            this.pesoR = value;
        }

        /**
         * Gets the value of the pesoBC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPesoBC() {
            return pesoBC;
        }

        /**
         * Sets the value of the pesoBC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPesoBC(String value) {
            this.pesoBC = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CNPJ" type="{http://www.portalfiscal.inf.br/cte}TCnpj"/>
     *         &lt;element name="cInt" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="10"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="IE" type="{http://www.portalfiscal.inf.br/cte}TIe" minOccurs="0"/>
     *         &lt;element name="xNome">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.portalfiscal.inf.br/cte}TString">
     *               &lt;maxLength value="60"/>
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="enderFerro" type="{http://www.portalfiscal.inf.br/cte}TEnderFer"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cnpj",
        "cInt",
        "ie",
        "xNome",
        "enderFerro"
    })
    public static class FerroEnv {

        @XmlElement(name = "CNPJ", required = true)
        protected String cnpj;
        protected String cInt;
        @XmlElement(name = "IE")
        protected String ie;
        @XmlElement(required = true)
        protected String xNome;
        @XmlElement(required = true)
        protected TEnderFer enderFerro;

        /**
         * Gets the value of the cnpj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCNPJ() {
            return cnpj;
        }

        /**
         * Sets the value of the cnpj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCNPJ(String value) {
            this.cnpj = value;
        }

        /**
         * Gets the value of the cInt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCInt() {
            return cInt;
        }

        /**
         * Sets the value of the cInt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCInt(String value) {
            this.cInt = value;
        }

        /**
         * Gets the value of the ie property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIE() {
            return ie;
        }

        /**
         * Sets the value of the ie property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIE(String value) {
            this.ie = value;
        }

        /**
         * Gets the value of the xNome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getXNome() {
            return xNome;
        }

        /**
         * Sets the value of the xNome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setXNome(String value) {
            this.xNome = value;
        }

        /**
         * Gets the value of the enderFerro property.
         * 
         * @return
         *     possible object is
         *     {@link TEnderFer }
         *     
         */
        public TEnderFer getEnderFerro() {
            return enderFerro;
        }

        /**
         * Sets the value of the enderFerro property.
         * 
         * @param value
         *     allowed object is
         *     {@link TEnderFer }
         *     
         */
        public void setEnderFerro(TEnderFer value) {
            this.enderFerro = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="respFat">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;whiteSpace value="preserve"/>
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ferrEmi">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;whiteSpace value="preserve"/>
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "respFat",
        "ferrEmi"
    })
    public static class TrafMut {

        @XmlElement(required = true)
        protected String respFat;
        @XmlElement(required = true)
        protected String ferrEmi;

        /**
         * Gets the value of the respFat property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRespFat() {
            return respFat;
        }

        /**
         * Sets the value of the respFat property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRespFat(String value) {
            this.respFat = value;
        }

        /**
         * Gets the value of the ferrEmi property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFerrEmi() {
            return ferrEmi;
        }

        /**
         * Sets the value of the ferrEmi property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFerrEmi(String value) {
            this.ferrEmi = value;
        }

    }

}
