//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.26 at 12:09:23 PM BRT 
//


package br.inf.portalfiscal.cte;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.inf.portalfiscal.cte package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RetConsSitCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "retConsSitCTe");
    private final static QName _RetEventoCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "retEventoCTe");
    private final static QName _ConsStatServCte_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "consStatServCte");
    private final static QName _ConsSitCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "consSitCTe");
    private final static QName _EnviCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "enviCTe");
    private final static QName _RetConsStatServCte_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "retConsStatServCte");
    private final static QName _ProcInutCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "procInutCTe");
    private final static QName _ConsReciCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "consReciCTe");
    private final static QName _InutCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "inutCTe");
    private final static QName _RetEnviCte_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "retEnviCte");
    private final static QName _RetConsReciCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "retConsReciCTe");
    private final static QName _CTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "CTe");
    private final static QName _EventoCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "eventoCTe");
    private final static QName _RetInutCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "retInutCTe");
    private final static QName _ProcEventoCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "procEventoCTe");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.inf.portalfiscal.cte
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EvCCeCTe }
     * 
     */
    public EvCCeCTe createEvCCeCTe() {
        return new EvCCeCTe();
    }

    /**
     * Create an instance of {@link EvEPECCTe }
     * 
     */
    public EvEPECCTe createEvEPECCTe() {
        return new EvEPECCTe();
    }

    /**
     * Create an instance of {@link Ferrov }
     * 
     */
    public Ferrov createFerrov() {
        return new Ferrov();
    }

    /**
     * Create an instance of {@link Aquav }
     * 
     */
    public Aquav createAquav() {
        return new Aquav();
    }

    /**
     * Create an instance of {@link Rodo }
     * 
     */
    public Rodo createRodo() {
        return new Rodo();
    }

    /**
     * Create an instance of {@link Aereo }
     * 
     */
    public Aereo createAereo() {
        return new Aereo();
    }

    /**
     * Create an instance of {@link TImp }
     * 
     */
    public TImp createTImp() {
        return new TImp();
    }

    /**
     * Create an instance of {@link TUnidadeTransp }
     * 
     */
    public TUnidadeTransp createTUnidadeTransp() {
        return new TUnidadeTransp();
    }

    /**
     * Create an instance of {@link TRetCancCTe }
     * 
     */
    public TRetCancCTe createTRetCancCTe() {
        return new TRetCancCTe();
    }

    /**
     * Create an instance of {@link TCancCTe }
     * 
     */
    public TCancCTe createTCancCTe() {
        return new TCancCTe();
    }

    /**
     * Create an instance of {@link TUnidCarga }
     * 
     */
    public TUnidCarga createTUnidCarga() {
        return new TUnidCarga();
    }

    /**
     * Create an instance of {@link Rodo.Veic }
     * 
     */
    public Rodo.Veic createRodoVeic() {
        return new Rodo.Veic();
    }

    /**
     * Create an instance of {@link Rodo.Occ }
     * 
     */
    public Rodo.Occ createRodoOcc() {
        return new Rodo.Occ();
    }

    /**
     * Create an instance of {@link TProtCTe }
     * 
     */
    public TProtCTe createTProtCTe() {
        return new TProtCTe();
    }

    /**
     * Create an instance of {@link Aquav.DetCont }
     * 
     */
    public Aquav.DetCont createAquavDetCont() {
        return new Aquav.DetCont();
    }

    /**
     * Create an instance of {@link Aquav.DetCont.InfDoc }
     * 
     */
    public Aquav.DetCont.InfDoc createAquavDetContInfDoc() {
        return new Aquav.DetCont.InfDoc();
    }

    /**
     * Create an instance of {@link TEvento }
     * 
     */
    public TEvento createTEvento() {
        return new TEvento();
    }

    /**
     * Create an instance of {@link TEvento.InfEvento }
     * 
     */
    public TEvento.InfEvento createTEventoInfEvento() {
        return new TEvento.InfEvento();
    }

    /**
     * Create an instance of {@link TInutCTe }
     * 
     */
    public TInutCTe createTInutCTe() {
        return new TInutCTe();
    }

    /**
     * Create an instance of {@link TRetEnviCTe }
     * 
     */
    public TRetEnviCTe createTRetEnviCTe() {
        return new TRetEnviCTe();
    }

    /**
     * Create an instance of {@link TCTe }
     * 
     */
    public TCTe createTCTe() {
        return new TCTe();
    }

    /**
     * Create an instance of {@link TCTe.InfCte }
     * 
     */
    public TCTe.InfCte createTCTeInfCte() {
        return new TCTe.InfCte();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm }
     * 
     */
    public TCTe.InfCte.InfCTeNorm createTCTeInfCteInfCTeNorm() {
        return new TCTe.InfCte.InfCTeNorm();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCteSub }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCteSub createTCTeInfCteInfCTeNormInfCteSub() {
        return new TCTe.InfCte.InfCTeNorm.InfCteSub();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS createTCTeInfCteInfCTeNormInfCteSubTomaICMS() {
        return new TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Cobr }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Cobr createTCTeInfCteInfCTeNormCobr() {
        return new TCTe.InfCte.InfCTeNorm.Cobr();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt createTCTeInfCteInfCTeNormDocAnt() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt createTCTeInfCteInfCTeNormDocAntEmiDocAnt() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt createTCTeInfCteInfCTeNormDocAntEmiDocAntIdDocAnt() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfDoc }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfDoc createTCTeInfCteInfCTeNormInfDoc() {
        return new TCTe.InfCte.InfCTeNorm.InfDoc();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCarga }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCarga createTCTeInfCteInfCTeNormInfCarga() {
        return new TCTe.InfCte.InfCTeNorm.InfCarga();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Imp }
     * 
     */
    public TCTe.InfCte.Imp createTCTeInfCteImp() {
        return new TCTe.InfCte.Imp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.VPrest }
     * 
     */
    public TCTe.InfCte.VPrest createTCTeInfCteVPrest() {
        return new TCTe.InfCte.VPrest();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl }
     * 
     */
    public TCTe.InfCte.Compl createTCTeInfCteCompl() {
        return new TCTe.InfCte.Compl();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega }
     * 
     */
    public TCTe.InfCte.Compl.Entrega createTCTeInfCteComplEntrega() {
        return new TCTe.InfCte.Compl.Entrega();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Fluxo }
     * 
     */
    public TCTe.InfCte.Compl.Fluxo createTCTeInfCteComplFluxo() {
        return new TCTe.InfCte.Compl.Fluxo();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Ide }
     * 
     */
    public TCTe.InfCte.Ide createTCTeInfCteIde() {
        return new TCTe.InfCte.Ide();
    }

    /**
     * Create an instance of {@link TRetInutCTe }
     * 
     */
    public TRetInutCTe createTRetInutCTe() {
        return new TRetInutCTe();
    }

    /**
     * Create an instance of {@link TRetEvento }
     * 
     */
    public TRetEvento createTRetEvento() {
        return new TRetEvento();
    }

    /**
     * Create an instance of {@link TEnviCTe }
     * 
     */
    public TEnviCTe createTEnviCTe() {
        return new TEnviCTe();
    }

    /**
     * Create an instance of {@link TConsStatServ }
     * 
     */
    public TConsStatServ createTConsStatServ() {
        return new TConsStatServ();
    }

    /**
     * Create an instance of {@link EvCCeCTe.InfCorrecao }
     * 
     */
    public EvCCeCTe.InfCorrecao createEvCCeCTeInfCorrecao() {
        return new EvCCeCTe.InfCorrecao();
    }

    /**
     * Create an instance of {@link TRetConsSitCTe }
     * 
     */
    public TRetConsSitCTe createTRetConsSitCTe() {
        return new TRetConsSitCTe();
    }

    /**
     * Create an instance of {@link EvEPECCTe.Toma04 }
     * 
     */
    public EvEPECCTe.Toma04 createEvEPECCTeToma04() {
        return new EvEPECCTe.Toma04();
    }

    /**
     * Create an instance of {@link TProcInutCTe }
     * 
     */
    public TProcInutCTe createTProcInutCTe() {
        return new TProcInutCTe();
    }

    /**
     * Create an instance of {@link Duto }
     * 
     */
    public Duto createDuto() {
        return new Duto();
    }

    /**
     * Create an instance of {@link TConsSitCTe }
     * 
     */
    public TConsSitCTe createTConsSitCTe() {
        return new TConsSitCTe();
    }

    /**
     * Create an instance of {@link Multimodal }
     * 
     */
    public Multimodal createMultimodal() {
        return new Multimodal();
    }

    /**
     * Create an instance of {@link TProcEvento }
     * 
     */
    public TProcEvento createTProcEvento() {
        return new TProcEvento();
    }

    /**
     * Create an instance of {@link Ferrov.TrafMut }
     * 
     */
    public Ferrov.TrafMut createFerrovTrafMut() {
        return new Ferrov.TrafMut();
    }

    /**
     * Create an instance of {@link Ferrov.FerroEnv }
     * 
     */
    public Ferrov.FerroEnv createFerrovFerroEnv() {
        return new Ferrov.FerroEnv();
    }

    /**
     * Create an instance of {@link Ferrov.DetVag }
     * 
     */
    public Ferrov.DetVag createFerrovDetVag() {
        return new Ferrov.DetVag();
    }

    /**
     * Create an instance of {@link Aquav.Balsa }
     * 
     */
    public Aquav.Balsa createAquavBalsa() {
        return new Aquav.Balsa();
    }

    /**
     * Create an instance of {@link EvRegMultimodal }
     * 
     */
    public EvRegMultimodal createEvRegMultimodal() {
        return new EvRegMultimodal();
    }

    /**
     * Create an instance of {@link CteProc }
     * 
     */
    public CteProc createCteProc() {
        return new CteProc();
    }

    /**
     * Create an instance of {@link TRetConsReciCTe }
     * 
     */
    public TRetConsReciCTe createTRetConsReciCTe() {
        return new TRetConsReciCTe();
    }

    /**
     * Create an instance of {@link TRetConsStatServ }
     * 
     */
    public TRetConsStatServ createTRetConsStatServ() {
        return new TRetConsStatServ();
    }

    /**
     * Create an instance of {@link Rodo.ValePed }
     * 
     */
    public Rodo.ValePed createRodoValePed() {
        return new Rodo.ValePed();
    }

    /**
     * Create an instance of {@link Rodo.LacRodo }
     * 
     */
    public Rodo.LacRodo createRodoLacRodo() {
        return new Rodo.LacRodo();
    }

    /**
     * Create an instance of {@link Rodo.Moto }
     * 
     */
    public Rodo.Moto createRodoMoto() {
        return new Rodo.Moto();
    }

    /**
     * Create an instance of {@link TConsReciCTe }
     * 
     */
    public TConsReciCTe createTConsReciCTe() {
        return new TConsReciCTe();
    }

    /**
     * Create an instance of {@link Aereo.Tarifa }
     * 
     */
    public Aereo.Tarifa createAereoTarifa() {
        return new Aereo.Tarifa();
    }

    /**
     * Create an instance of {@link Aereo.NatCarga }
     * 
     */
    public Aereo.NatCarga createAereoNatCarga() {
        return new Aereo.NatCarga();
    }

    /**
     * Create an instance of {@link EvCancCTe }
     * 
     */
    public EvCancCTe createEvCancCTe() {
        return new EvCancCTe();
    }

    /**
     * Create an instance of {@link TEndereco }
     * 
     */
    public TEndereco createTEndereco() {
        return new TEndereco();
    }

    /**
     * Create an instance of {@link TProcCancCTe }
     * 
     */
    public TProcCancCTe createTProcCancCTe() {
        return new TProcCancCTe();
    }

    /**
     * Create an instance of {@link TEnderFer }
     * 
     */
    public TEnderFer createTEnderFer() {
        return new TEnderFer();
    }

    /**
     * Create an instance of {@link TEndReEnt }
     * 
     */
    public TEndReEnt createTEndReEnt() {
        return new TEndReEnt();
    }

    /**
     * Create an instance of {@link TEndernac }
     * 
     */
    public TEndernac createTEndernac() {
        return new TEndernac();
    }

    /**
     * Create an instance of {@link TLocal }
     * 
     */
    public TLocal createTLocal() {
        return new TLocal();
    }

    /**
     * Create an instance of {@link TEndeEmi }
     * 
     */
    public TEndeEmi createTEndeEmi() {
        return new TEndeEmi();
    }

    /**
     * Create an instance of {@link TEndOrg }
     * 
     */
    public TEndOrg createTEndOrg() {
        return new TEndOrg();
    }

    /**
     * Create an instance of {@link TImp.ICMS00 }
     * 
     */
    public TImp.ICMS00 createTImpICMS00() {
        return new TImp.ICMS00();
    }

    /**
     * Create an instance of {@link TImp.ICMS20 }
     * 
     */
    public TImp.ICMS20 createTImpICMS20() {
        return new TImp.ICMS20();
    }

    /**
     * Create an instance of {@link TImp.ICMS45 }
     * 
     */
    public TImp.ICMS45 createTImpICMS45() {
        return new TImp.ICMS45();
    }

    /**
     * Create an instance of {@link TImp.ICMS60 }
     * 
     */
    public TImp.ICMS60 createTImpICMS60() {
        return new TImp.ICMS60();
    }

    /**
     * Create an instance of {@link TImp.ICMS90 }
     * 
     */
    public TImp.ICMS90 createTImpICMS90() {
        return new TImp.ICMS90();
    }

    /**
     * Create an instance of {@link TImp.ICMSOutraUF }
     * 
     */
    public TImp.ICMSOutraUF createTImpICMSOutraUF() {
        return new TImp.ICMSOutraUF();
    }

    /**
     * Create an instance of {@link TImp.ICMSSN }
     * 
     */
    public TImp.ICMSSN createTImpICMSSN() {
        return new TImp.ICMSSN();
    }

    /**
     * Create an instance of {@link TUnidadeTransp.LacUnidTransp }
     * 
     */
    public TUnidadeTransp.LacUnidTransp createTUnidadeTranspLacUnidTransp() {
        return new TUnidadeTransp.LacUnidTransp();
    }

    /**
     * Create an instance of {@link TRetCancCTe.InfCanc }
     * 
     */
    public TRetCancCTe.InfCanc createTRetCancCTeInfCanc() {
        return new TRetCancCTe.InfCanc();
    }

    /**
     * Create an instance of {@link TCancCTe.InfCanc }
     * 
     */
    public TCancCTe.InfCanc createTCancCTeInfCanc() {
        return new TCancCTe.InfCanc();
    }

    /**
     * Create an instance of {@link TUnidCarga.LacUnidCarga }
     * 
     */
    public TUnidCarga.LacUnidCarga createTUnidCargaLacUnidCarga() {
        return new TUnidCarga.LacUnidCarga();
    }

    /**
     * Create an instance of {@link Rodo.Veic.Prop }
     * 
     */
    public Rodo.Veic.Prop createRodoVeicProp() {
        return new Rodo.Veic.Prop();
    }

    /**
     * Create an instance of {@link Rodo.Occ.EmiOcc }
     * 
     */
    public Rodo.Occ.EmiOcc createRodoOccEmiOcc() {
        return new Rodo.Occ.EmiOcc();
    }

    /**
     * Create an instance of {@link TProtCTe.InfProt }
     * 
     */
    public TProtCTe.InfProt createTProtCTeInfProt() {
        return new TProtCTe.InfProt();
    }

    /**
     * Create an instance of {@link Aquav.DetCont.Lacre }
     * 
     */
    public Aquav.DetCont.Lacre createAquavDetContLacre() {
        return new Aquav.DetCont.Lacre();
    }

    /**
     * Create an instance of {@link Aquav.DetCont.InfDoc.InfNF }
     * 
     */
    public Aquav.DetCont.InfDoc.InfNF createAquavDetContInfDocInfNF() {
        return new Aquav.DetCont.InfDoc.InfNF();
    }

    /**
     * Create an instance of {@link Aquav.DetCont.InfDoc.InfNFe }
     * 
     */
    public Aquav.DetCont.InfDoc.InfNFe createAquavDetContInfDocInfNFe() {
        return new Aquav.DetCont.InfDoc.InfNFe();
    }

    /**
     * Create an instance of {@link TEvento.InfEvento.DetEvento }
     * 
     */
    public TEvento.InfEvento.DetEvento createTEventoInfEventoDetEvento() {
        return new TEvento.InfEvento.DetEvento();
    }

    /**
     * Create an instance of {@link TInutCTe.InfInut }
     * 
     */
    public TInutCTe.InfInut createTInutCTeInfInut() {
        return new TInutCTe.InfInut();
    }

    /**
     * Create an instance of {@link TRetEnviCTe.InfRec }
     * 
     */
    public TRetEnviCTe.InfRec createTRetEnviCTeInfRec() {
        return new TRetEnviCTe.InfRec();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Emit }
     * 
     */
    public TCTe.InfCte.Emit createTCTeInfCteEmit() {
        return new TCTe.InfCte.Emit();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Rem }
     * 
     */
    public TCTe.InfCte.Rem createTCTeInfCteRem() {
        return new TCTe.InfCte.Rem();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Exped }
     * 
     */
    public TCTe.InfCte.Exped createTCTeInfCteExped() {
        return new TCTe.InfCte.Exped();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Receb }
     * 
     */
    public TCTe.InfCte.Receb createTCTeInfCteReceb() {
        return new TCTe.InfCte.Receb();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Dest }
     * 
     */
    public TCTe.InfCte.Dest createTCTeInfCteDest() {
        return new TCTe.InfCte.Dest();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCteComp }
     * 
     */
    public TCTe.InfCte.InfCteComp createTCTeInfCteInfCteComp() {
        return new TCTe.InfCte.InfCteComp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCteAnu }
     * 
     */
    public TCTe.InfCte.InfCteAnu createTCTeInfCteInfCteAnu() {
        return new TCTe.InfCte.InfCteAnu();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.AutXML }
     * 
     */
    public TCTe.InfCte.AutXML createTCTeInfCteAutXML() {
        return new TCTe.InfCte.AutXML();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Seg }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Seg createTCTeInfCteInfCTeNormSeg() {
        return new TCTe.InfCte.InfCTeNorm.Seg();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfModal }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfModal createTCTeInfCteInfCTeNormInfModal() {
        return new TCTe.InfCte.InfCTeNorm.InfModal();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Peri }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Peri createTCTeInfCteInfCTeNormPeri() {
        return new TCTe.InfCte.InfCTeNorm.Peri();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.VeicNovos }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.VeicNovos createTCTeInfCteInfCTeNormVeicNovos() {
        return new TCTe.InfCte.InfCTeNorm.VeicNovos();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCteSub.TomaNaoICMS }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCteSub.TomaNaoICMS createTCTeInfCteInfCTeNormInfCteSubTomaNaoICMS() {
        return new TCTe.InfCte.InfCTeNorm.InfCteSub.TomaNaoICMS();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS.RefNF }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS.RefNF createTCTeInfCteInfCTeNormInfCteSubTomaICMSRefNF() {
        return new TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS.RefNF();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Cobr.Fat }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Cobr.Fat createTCTeInfCteInfCTeNormCobrFat() {
        return new TCTe.InfCte.InfCTeNorm.Cobr.Fat();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Cobr.Dup }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Cobr.Dup createTCTeInfCteInfCTeNormCobrDup() {
        return new TCTe.InfCte.InfCTeNorm.Cobr.Dup();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntPap }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntPap createTCTeInfCteInfCTeNormDocAntEmiDocAntIdDocAntIdDocAntPap() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntPap();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntEle }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntEle createTCTeInfCteInfCTeNormDocAntEmiDocAntIdDocAntIdDocAntEle() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntEle();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfDoc.InfNF }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfDoc.InfNF createTCTeInfCteInfCTeNormInfDocInfNF() {
        return new TCTe.InfCte.InfCTeNorm.InfDoc.InfNF();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfDoc.InfNFe }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfDoc.InfNFe createTCTeInfCteInfCTeNormInfDocInfNFe() {
        return new TCTe.InfCte.InfCTeNorm.InfDoc.InfNFe();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfDoc.InfOutros }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfDoc.InfOutros createTCTeInfCteInfCTeNormInfDocInfOutros() {
        return new TCTe.InfCte.InfCTeNorm.InfDoc.InfOutros();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCarga.InfQ }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCarga.InfQ createTCTeInfCteInfCTeNormInfCargaInfQ() {
        return new TCTe.InfCte.InfCTeNorm.InfCarga.InfQ();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Imp.ICMSUFFim }
     * 
     */
    public TCTe.InfCte.Imp.ICMSUFFim createTCTeInfCteImpICMSUFFim() {
        return new TCTe.InfCte.Imp.ICMSUFFim();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.VPrest.Comp }
     * 
     */
    public TCTe.InfCte.VPrest.Comp createTCTeInfCteVPrestComp() {
        return new TCTe.InfCte.VPrest.Comp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.ObsCont }
     * 
     */
    public TCTe.InfCte.Compl.ObsCont createTCTeInfCteComplObsCont() {
        return new TCTe.InfCte.Compl.ObsCont();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.ObsFisco }
     * 
     */
    public TCTe.InfCte.Compl.ObsFisco createTCTeInfCteComplObsFisco() {
        return new TCTe.InfCte.Compl.ObsFisco();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.SemData }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.SemData createTCTeInfCteComplEntregaSemData() {
        return new TCTe.InfCte.Compl.Entrega.SemData();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.ComData }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.ComData createTCTeInfCteComplEntregaComData() {
        return new TCTe.InfCte.Compl.Entrega.ComData();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.NoPeriodo }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.NoPeriodo createTCTeInfCteComplEntregaNoPeriodo() {
        return new TCTe.InfCte.Compl.Entrega.NoPeriodo();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.SemHora }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.SemHora createTCTeInfCteComplEntregaSemHora() {
        return new TCTe.InfCte.Compl.Entrega.SemHora();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.ComHora }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.ComHora createTCTeInfCteComplEntregaComHora() {
        return new TCTe.InfCte.Compl.Entrega.ComHora();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.NoInter }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.NoInter createTCTeInfCteComplEntregaNoInter() {
        return new TCTe.InfCte.Compl.Entrega.NoInter();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Fluxo.Pass }
     * 
     */
    public TCTe.InfCte.Compl.Fluxo.Pass createTCTeInfCteComplFluxoPass() {
        return new TCTe.InfCte.Compl.Fluxo.Pass();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Ide.Toma03 }
     * 
     */
    public TCTe.InfCte.Ide.Toma03 createTCTeInfCteIdeToma03() {
        return new TCTe.InfCte.Ide.Toma03();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Ide.Toma4 }
     * 
     */
    public TCTe.InfCte.Ide.Toma4 createTCTeInfCteIdeToma4() {
        return new TCTe.InfCte.Ide.Toma4();
    }

    /**
     * Create an instance of {@link TRetInutCTe.InfInut }
     * 
     */
    public TRetInutCTe.InfInut createTRetInutCTeInfInut() {
        return new TRetInutCTe.InfInut();
    }

    /**
     * Create an instance of {@link TRetEvento.InfEvento }
     * 
     */
    public TRetEvento.InfEvento createTRetEventoInfEvento() {
        return new TRetEvento.InfEvento();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetConsSitCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "retConsSitCTe")
    public JAXBElement<TRetConsSitCTe> createRetConsSitCTe(TRetConsSitCTe value) {
        return new JAXBElement<TRetConsSitCTe>(_RetConsSitCTe_QNAME, TRetConsSitCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetEvento }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "retEventoCTe")
    public JAXBElement<TRetEvento> createRetEventoCTe(TRetEvento value) {
        return new JAXBElement<TRetEvento>(_RetEventoCTe_QNAME, TRetEvento.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TConsStatServ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "consStatServCte")
    public JAXBElement<TConsStatServ> createConsStatServCte(TConsStatServ value) {
        return new JAXBElement<TConsStatServ>(_ConsStatServCte_QNAME, TConsStatServ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TConsSitCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "consSitCTe")
    public JAXBElement<TConsSitCTe> createConsSitCTe(TConsSitCTe value) {
        return new JAXBElement<TConsSitCTe>(_ConsSitCTe_QNAME, TConsSitCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TEnviCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "enviCTe")
    public JAXBElement<TEnviCTe> createEnviCTe(TEnviCTe value) {
        return new JAXBElement<TEnviCTe>(_EnviCTe_QNAME, TEnviCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetConsStatServ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "retConsStatServCte")
    public JAXBElement<TRetConsStatServ> createRetConsStatServCte(TRetConsStatServ value) {
        return new JAXBElement<TRetConsStatServ>(_RetConsStatServCte_QNAME, TRetConsStatServ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProcInutCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "procInutCTe")
    public JAXBElement<TProcInutCTe> createProcInutCTe(TProcInutCTe value) {
        return new JAXBElement<TProcInutCTe>(_ProcInutCTe_QNAME, TProcInutCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TConsReciCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "consReciCTe")
    public JAXBElement<TConsReciCTe> createConsReciCTe(TConsReciCTe value) {
        return new JAXBElement<TConsReciCTe>(_ConsReciCTe_QNAME, TConsReciCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInutCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "inutCTe")
    public JAXBElement<TInutCTe> createInutCTe(TInutCTe value) {
        return new JAXBElement<TInutCTe>(_InutCTe_QNAME, TInutCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetEnviCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "retEnviCte")
    public JAXBElement<TRetEnviCTe> createRetEnviCte(TRetEnviCTe value) {
        return new JAXBElement<TRetEnviCTe>(_RetEnviCte_QNAME, TRetEnviCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetConsReciCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "retConsReciCTe")
    public JAXBElement<TRetConsReciCTe> createRetConsReciCTe(TRetConsReciCTe value) {
        return new JAXBElement<TRetConsReciCTe>(_RetConsReciCTe_QNAME, TRetConsReciCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "CTe")
    public JAXBElement<TCTe> createCTe(TCTe value) {
        return new JAXBElement<TCTe>(_CTe_QNAME, TCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TEvento }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "eventoCTe")
    public JAXBElement<TEvento> createEventoCTe(TEvento value) {
        return new JAXBElement<TEvento>(_EventoCTe_QNAME, TEvento.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetInutCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "retInutCTe")
    public JAXBElement<TRetInutCTe> createRetInutCTe(TRetInutCTe value) {
        return new JAXBElement<TRetInutCTe>(_RetInutCTe_QNAME, TRetInutCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProcEvento }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "procEventoCTe")
    public JAXBElement<TProcEvento> createProcEventoCTe(TProcEvento value) {
        return new JAXBElement<TProcEvento>(_ProcEventoCTe_QNAME, TProcEvento.class, null, value);
    }

}
