//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.25 at 11:36:19 PM BRT 
//


package br.inf.portalfiscal.cte;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.inf.portalfiscal.cte package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConsStatServCte_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "consStatServCte");
    private final static QName _CTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "CTe");
    private final static QName _ProcCancCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "procCancCTe");
    private final static QName _EnviCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "enviCTe");
    private final static QName _RetCancCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "retCancCTe");
    private final static QName _RetEnviCte_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "retEnviCte");
    private final static QName _RetConsStatServCte_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "retConsStatServCte");
    private final static QName _RetInutCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "retInutCTe");
    private final static QName _InutCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "inutCTe");
    private final static QName _RetConsSitCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "retConsSitCTe");
    private final static QName _ProcInutCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "procInutCTe");
    private final static QName _CancCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "cancCTe");
    private final static QName _RetConsReciCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "retConsReciCTe");
    private final static QName _ConsReciCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "consReciCTe");
    private final static QName _ConsSitCTe_QNAME = new QName("http://www.portalfiscal.inf.br/cte", "consSitCTe");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.inf.portalfiscal.cte
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TCST }
     * 
     */
    public TCST createTCST() {
        return new TCST();
    }

    /**
     * Create an instance of {@link TCancCTe }
     * 
     */
    public TCancCTe createTCancCTe() {
        return new TCancCTe();
    }

    /**
     * Create an instance of {@link TInutCTe }
     * 
     */
    public TInutCTe createTInutCTe() {
        return new TInutCTe();
    }

    /**
     * Create an instance of {@link TProtCTe }
     * 
     */
    public TProtCTe createTProtCTe() {
        return new TProtCTe();
    }

    /**
     * Create an instance of {@link TCTe }
     * 
     */
    public TCTe createTCTe() {
        return new TCTe();
    }

    /**
     * Create an instance of {@link TCTe.InfCte }
     * 
     */
    public TCTe.InfCte createTCTeInfCte() {
        return new TCTe.InfCte();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCteComp }
     * 
     */
    public TCTe.InfCte.InfCteComp createTCTeInfCteInfCteComp() {
        return new TCTe.InfCte.InfCteComp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCteComp.VPresComp }
     * 
     */
    public TCTe.InfCte.InfCteComp.VPresComp createTCTeInfCteInfCteCompVPresComp() {
        return new TCTe.InfCte.InfCteComp.VPresComp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm }
     * 
     */
    public TCTe.InfCte.InfCTeNorm createTCTeInfCteInfCTeNorm() {
        return new TCTe.InfCte.InfCTeNorm();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCteSub }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCteSub createTCTeInfCteInfCTeNormInfCteSub() {
        return new TCTe.InfCte.InfCTeNorm.InfCteSub();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS createTCTeInfCteInfCTeNormInfCteSubTomaICMS() {
        return new TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Ferrov }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Ferrov createTCTeInfCteInfCTeNormFerrov() {
        return new TCTe.InfCte.InfCTeNorm.Ferrov();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Ferrov.DetVag }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Ferrov.DetVag createTCTeInfCteInfCTeNormFerrovDetVag() {
        return new TCTe.InfCte.InfCTeNorm.Ferrov.DetVag();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Ferrov.DCL }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Ferrov.DCL createTCTeInfCteInfCTeNormFerrovDCL() {
        return new TCTe.InfCte.InfCTeNorm.Ferrov.DCL();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Ferrov.DCL.DetVagDCL }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Ferrov.DCL.DetVagDCL createTCTeInfCteInfCTeNormFerrovDCLDetVagDCL() {
        return new TCTe.InfCte.InfCTeNorm.Ferrov.DCL.DetVagDCL();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Aquav }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Aquav createTCTeInfCteInfCTeNormAquav() {
        return new TCTe.InfCte.InfCTeNorm.Aquav();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Aereo }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Aereo createTCTeInfCteInfCTeNormAereo() {
        return new TCTe.InfCte.InfCTeNorm.Aereo();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Rodo }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Rodo createTCTeInfCteInfCTeNormRodo() {
        return new TCTe.InfCte.InfCTeNorm.Rodo();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Rodo.Veic }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Rodo.Veic createTCTeInfCteInfCTeNormRodoVeic() {
        return new TCTe.InfCte.InfCTeNorm.Rodo.Veic();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Rodo.ValePed }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Rodo.ValePed createTCTeInfCteInfCTeNormRodoValePed() {
        return new TCTe.InfCte.InfCTeNorm.Rodo.ValePed();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Rodo.Occ }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Rodo.Occ createTCTeInfCteInfCTeNormRodoOcc() {
        return new TCTe.InfCte.InfCTeNorm.Rodo.Occ();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt createTCTeInfCteInfCTeNormDocAnt() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt createTCTeInfCteInfCTeNormDocAntEmiDocAnt() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt createTCTeInfCteInfCTeNormDocAntEmiDocAntIdDocAnt() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.ContQt }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.ContQt createTCTeInfCteInfCTeNormContQt() {
        return new TCTe.InfCte.InfCTeNorm.ContQt();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCarga }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCarga createTCTeInfCteInfCTeNormInfCarga() {
        return new TCTe.InfCte.InfCTeNorm.InfCarga();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.VPrest }
     * 
     */
    public TCTe.InfCte.VPrest createTCTeInfCteVPrest() {
        return new TCTe.InfCte.VPrest();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Rem }
     * 
     */
    public TCTe.InfCte.Rem createTCTeInfCteRem() {
        return new TCTe.InfCte.Rem();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl }
     * 
     */
    public TCTe.InfCte.Compl createTCTeInfCteCompl() {
        return new TCTe.InfCte.Compl();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega }
     * 
     */
    public TCTe.InfCte.Compl.Entrega createTCTeInfCteComplEntrega() {
        return new TCTe.InfCte.Compl.Entrega();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Fluxo }
     * 
     */
    public TCTe.InfCte.Compl.Fluxo createTCTeInfCteComplFluxo() {
        return new TCTe.InfCte.Compl.Fluxo();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Ide }
     * 
     */
    public TCTe.InfCte.Ide createTCTeInfCteIde() {
        return new TCTe.InfCte.Ide();
    }

    /**
     * Create an instance of {@link TRetInutCTe }
     * 
     */
    public TRetInutCTe createTRetInutCTe() {
        return new TRetInutCTe();
    }

    /**
     * Create an instance of {@link TRetEnviCTe }
     * 
     */
    public TRetEnviCTe createTRetEnviCTe() {
        return new TRetEnviCTe();
    }

    /**
     * Create an instance of {@link TRetCancCTe }
     * 
     */
    public TRetCancCTe createTRetCancCTe() {
        return new TRetCancCTe();
    }

    /**
     * Create an instance of {@link TEnviCTe }
     * 
     */
    public TEnviCTe createTEnviCTe() {
        return new TEnviCTe();
    }

    /**
     * Create an instance of {@link TRetConsStatServ }
     * 
     */
    public TRetConsStatServ createTRetConsStatServ() {
        return new TRetConsStatServ();
    }

    /**
     * Create an instance of {@link TConsStatServ }
     * 
     */
    public TConsStatServ createTConsStatServ() {
        return new TConsStatServ();
    }

    /**
     * Create an instance of {@link TProcCancCTe }
     * 
     */
    public TProcCancCTe createTProcCancCTe() {
        return new TProcCancCTe();
    }

    /**
     * Create an instance of {@link CteProc }
     * 
     */
    public CteProc createCteProc() {
        return new CteProc();
    }

    /**
     * Create an instance of {@link TConsSitCTe }
     * 
     */
    public TConsSitCTe createTConsSitCTe() {
        return new TConsSitCTe();
    }

    /**
     * Create an instance of {@link TRetConsReciCTe }
     * 
     */
    public TRetConsReciCTe createTRetConsReciCTe() {
        return new TRetConsReciCTe();
    }

    /**
     * Create an instance of {@link TConsReciCTe }
     * 
     */
    public TConsReciCTe createTConsReciCTe() {
        return new TConsReciCTe();
    }

    /**
     * Create an instance of {@link TRetConsSitCTe }
     * 
     */
    public TRetConsSitCTe createTRetConsSitCTe() {
        return new TRetConsSitCTe();
    }

    /**
     * Create an instance of {@link TProcInutCTe }
     * 
     */
    public TProcInutCTe createTProcInutCTe() {
        return new TProcInutCTe();
    }

    /**
     * Create an instance of {@link TEndernac }
     * 
     */
    public TEndernac createTEndernac() {
        return new TEndernac();
    }

    /**
     * Create an instance of {@link TLocal }
     * 
     */
    public TLocal createTLocal() {
        return new TLocal();
    }

    /**
     * Create an instance of {@link TEndeEmi }
     * 
     */
    public TEndeEmi createTEndeEmi() {
        return new TEndeEmi();
    }

    /**
     * Create an instance of {@link TEnderFer }
     * 
     */
    public TEnderFer createTEnderFer() {
        return new TEnderFer();
    }

    /**
     * Create an instance of {@link TEndReEnt }
     * 
     */
    public TEndReEnt createTEndReEnt() {
        return new TEndReEnt();
    }

    /**
     * Create an instance of {@link TEndereco }
     * 
     */
    public TEndereco createTEndereco() {
        return new TEndereco();
    }

    /**
     * Create an instance of {@link TEndOrg }
     * 
     */
    public TEndOrg createTEndOrg() {
        return new TEndOrg();
    }

    /**
     * Create an instance of {@link TCST.CST00 }
     * 
     */
    public TCST.CST00 createTCSTCST00() {
        return new TCST.CST00();
    }

    /**
     * Create an instance of {@link TCST.CST20 }
     * 
     */
    public TCST.CST20 createTCSTCST20() {
        return new TCST.CST20();
    }

    /**
     * Create an instance of {@link TCST.CST45 }
     * 
     */
    public TCST.CST45 createTCSTCST45() {
        return new TCST.CST45();
    }

    /**
     * Create an instance of {@link TCST.CST80 }
     * 
     */
    public TCST.CST80 createTCSTCST80() {
        return new TCST.CST80();
    }

    /**
     * Create an instance of {@link TCST.CST81 }
     * 
     */
    public TCST.CST81 createTCSTCST81() {
        return new TCST.CST81();
    }

    /**
     * Create an instance of {@link TCST.CST90 }
     * 
     */
    public TCST.CST90 createTCSTCST90() {
        return new TCST.CST90();
    }

    /**
     * Create an instance of {@link TCancCTe.InfCanc }
     * 
     */
    public TCancCTe.InfCanc createTCancCTeInfCanc() {
        return new TCancCTe.InfCanc();
    }

    /**
     * Create an instance of {@link TInutCTe.InfInut }
     * 
     */
    public TInutCTe.InfInut createTInutCTeInfInut() {
        return new TInutCTe.InfInut();
    }

    /**
     * Create an instance of {@link TProtCTe.InfProt }
     * 
     */
    public TProtCTe.InfProt createTProtCTeInfProt() {
        return new TProtCTe.InfProt();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Emit }
     * 
     */
    public TCTe.InfCte.Emit createTCTeInfCteEmit() {
        return new TCTe.InfCte.Emit();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Exped }
     * 
     */
    public TCTe.InfCte.Exped createTCTeInfCteExped() {
        return new TCTe.InfCte.Exped();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Receb }
     * 
     */
    public TCTe.InfCte.Receb createTCTeInfCteReceb() {
        return new TCTe.InfCte.Receb();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Dest }
     * 
     */
    public TCTe.InfCte.Dest createTCTeInfCteDest() {
        return new TCTe.InfCte.Dest();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Imp }
     * 
     */
    public TCTe.InfCte.Imp createTCTeInfCteImp() {
        return new TCTe.InfCte.Imp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCteAnu }
     * 
     */
    public TCTe.InfCte.InfCteAnu createTCTeInfCteInfCteAnu() {
        return new TCTe.InfCte.InfCteAnu();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCteComp.ImpComp }
     * 
     */
    public TCTe.InfCte.InfCteComp.ImpComp createTCTeInfCteInfCteCompImpComp() {
        return new TCTe.InfCte.InfCteComp.ImpComp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCteComp.VPresComp.CompComp }
     * 
     */
    public TCTe.InfCte.InfCteComp.VPresComp.CompComp createTCTeInfCteInfCteCompVPresCompCompComp() {
        return new TCTe.InfCte.InfCteComp.VPresComp.CompComp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Seg }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Seg createTCTeInfCteInfCTeNormSeg() {
        return new TCTe.InfCte.InfCTeNorm.Seg();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Duto }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Duto createTCTeInfCteInfCTeNormDuto() {
        return new TCTe.InfCte.InfCTeNorm.Duto();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Peri }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Peri createTCTeInfCteInfCTeNormPeri() {
        return new TCTe.InfCte.InfCTeNorm.Peri();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.VeicNovos }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.VeicNovos createTCTeInfCteInfCTeNormVeicNovos() {
        return new TCTe.InfCte.InfCTeNorm.VeicNovos();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCteSub.TomaNaoICMS }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCteSub.TomaNaoICMS createTCTeInfCteInfCTeNormInfCteSubTomaNaoICMS() {
        return new TCTe.InfCte.InfCTeNorm.InfCteSub.TomaNaoICMS();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS.RefNF }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS.RefNF createTCTeInfCteInfCTeNormInfCteSubTomaICMSRefNF() {
        return new TCTe.InfCte.InfCTeNorm.InfCteSub.TomaICMS.RefNF();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Ferrov.FerroSub }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Ferrov.FerroSub createTCTeInfCteInfCTeNormFerrovFerroSub() {
        return new TCTe.InfCte.InfCTeNorm.Ferrov.FerroSub();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Ferrov.DetVag.LacDetVag }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Ferrov.DetVag.LacDetVag createTCTeInfCteInfCTeNormFerrovDetVagLacDetVag() {
        return new TCTe.InfCte.InfCTeNorm.Ferrov.DetVag.LacDetVag();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Ferrov.DetVag.ContVag }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Ferrov.DetVag.ContVag createTCTeInfCteInfCTeNormFerrovDetVagContVag() {
        return new TCTe.InfCte.InfCTeNorm.Ferrov.DetVag.ContVag();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Ferrov.DCL.DetVagDCL.LacDetVagDCL }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Ferrov.DCL.DetVagDCL.LacDetVagDCL createTCTeInfCteInfCTeNormFerrovDCLDetVagDCLLacDetVagDCL() {
        return new TCTe.InfCte.InfCTeNorm.Ferrov.DCL.DetVagDCL.LacDetVagDCL();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Ferrov.DCL.DetVagDCL.ContDCL }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Ferrov.DCL.DetVagDCL.ContDCL createTCTeInfCteInfCTeNormFerrovDCLDetVagDCLContDCL() {
        return new TCTe.InfCte.InfCTeNorm.Ferrov.DCL.DetVagDCL.ContDCL();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Aquav.Lacre }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Aquav.Lacre createTCTeInfCteInfCTeNormAquavLacre() {
        return new TCTe.InfCte.InfCTeNorm.Aquav.Lacre();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Aereo.Tarifa }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Aereo.Tarifa createTCTeInfCteInfCTeNormAereoTarifa() {
        return new TCTe.InfCte.InfCTeNorm.Aereo.Tarifa();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Rodo.CTRB }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Rodo.CTRB createTCTeInfCteInfCTeNormRodoCTRB() {
        return new TCTe.InfCte.InfCTeNorm.Rodo.CTRB();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Rodo.LacRodo }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Rodo.LacRodo createTCTeInfCteInfCTeNormRodoLacRodo() {
        return new TCTe.InfCte.InfCTeNorm.Rodo.LacRodo();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Rodo.Moto }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Rodo.Moto createTCTeInfCteInfCTeNormRodoMoto() {
        return new TCTe.InfCte.InfCTeNorm.Rodo.Moto();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Rodo.Veic.Prop }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Rodo.Veic.Prop createTCTeInfCteInfCTeNormRodoVeicProp() {
        return new TCTe.InfCte.InfCTeNorm.Rodo.Veic.Prop();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Rodo.ValePed.Disp }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Rodo.ValePed.Disp createTCTeInfCteInfCTeNormRodoValePedDisp() {
        return new TCTe.InfCte.InfCTeNorm.Rodo.ValePed.Disp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.Rodo.Occ.EmiOcc }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.Rodo.Occ.EmiOcc createTCTeInfCteInfCTeNormRodoOccEmiOcc() {
        return new TCTe.InfCte.InfCTeNorm.Rodo.Occ.EmiOcc();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntPap }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntPap createTCTeInfCteInfCTeNormDocAntEmiDocAntIdDocAntIdDocAntPap() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntPap();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntEle }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntEle createTCTeInfCteInfCTeNormDocAntEmiDocAntIdDocAntIdDocAntEle() {
        return new TCTe.InfCte.InfCTeNorm.DocAnt.EmiDocAnt.IdDocAnt.IdDocAntEle();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.ContQt.LacContQt }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.ContQt.LacContQt createTCTeInfCteInfCTeNormContQtLacContQt() {
        return new TCTe.InfCte.InfCTeNorm.ContQt.LacContQt();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.InfCTeNorm.InfCarga.InfQ }
     * 
     */
    public TCTe.InfCte.InfCTeNorm.InfCarga.InfQ createTCTeInfCteInfCTeNormInfCargaInfQ() {
        return new TCTe.InfCte.InfCTeNorm.InfCarga.InfQ();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.VPrest.Comp }
     * 
     */
    public TCTe.InfCte.VPrest.Comp createTCTeInfCteVPrestComp() {
        return new TCTe.InfCte.VPrest.Comp();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Rem.InfNF }
     * 
     */
    public TCTe.InfCte.Rem.InfNF createTCTeInfCteRemInfNF() {
        return new TCTe.InfCte.Rem.InfNF();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Rem.InfNFe }
     * 
     */
    public TCTe.InfCte.Rem.InfNFe createTCTeInfCteRemInfNFe() {
        return new TCTe.InfCte.Rem.InfNFe();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Rem.InfOutros }
     * 
     */
    public TCTe.InfCte.Rem.InfOutros createTCTeInfCteRemInfOutros() {
        return new TCTe.InfCte.Rem.InfOutros();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.ObsCont }
     * 
     */
    public TCTe.InfCte.Compl.ObsCont createTCTeInfCteComplObsCont() {
        return new TCTe.InfCte.Compl.ObsCont();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.ObsFisco }
     * 
     */
    public TCTe.InfCte.Compl.ObsFisco createTCTeInfCteComplObsFisco() {
        return new TCTe.InfCte.Compl.ObsFisco();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.SemData }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.SemData createTCTeInfCteComplEntregaSemData() {
        return new TCTe.InfCte.Compl.Entrega.SemData();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.ComData }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.ComData createTCTeInfCteComplEntregaComData() {
        return new TCTe.InfCte.Compl.Entrega.ComData();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.NoPeriodo }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.NoPeriodo createTCTeInfCteComplEntregaNoPeriodo() {
        return new TCTe.InfCte.Compl.Entrega.NoPeriodo();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.SemHora }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.SemHora createTCTeInfCteComplEntregaSemHora() {
        return new TCTe.InfCte.Compl.Entrega.SemHora();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.ComHora }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.ComHora createTCTeInfCteComplEntregaComHora() {
        return new TCTe.InfCte.Compl.Entrega.ComHora();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Entrega.NoInter }
     * 
     */
    public TCTe.InfCte.Compl.Entrega.NoInter createTCTeInfCteComplEntregaNoInter() {
        return new TCTe.InfCte.Compl.Entrega.NoInter();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Compl.Fluxo.Pass }
     * 
     */
    public TCTe.InfCte.Compl.Fluxo.Pass createTCTeInfCteComplFluxoPass() {
        return new TCTe.InfCte.Compl.Fluxo.Pass();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Ide.Toma03 }
     * 
     */
    public TCTe.InfCte.Ide.Toma03 createTCTeInfCteIdeToma03() {
        return new TCTe.InfCte.Ide.Toma03();
    }

    /**
     * Create an instance of {@link TCTe.InfCte.Ide.Toma4 }
     * 
     */
    public TCTe.InfCte.Ide.Toma4 createTCTeInfCteIdeToma4() {
        return new TCTe.InfCte.Ide.Toma4();
    }

    /**
     * Create an instance of {@link TRetInutCTe.InfInut }
     * 
     */
    public TRetInutCTe.InfInut createTRetInutCTeInfInut() {
        return new TRetInutCTe.InfInut();
    }

    /**
     * Create an instance of {@link TRetEnviCTe.InfRec }
     * 
     */
    public TRetEnviCTe.InfRec createTRetEnviCTeInfRec() {
        return new TRetEnviCTe.InfRec();
    }

    /**
     * Create an instance of {@link TRetCancCTe.InfCanc }
     * 
     */
    public TRetCancCTe.InfCanc createTRetCancCTeInfCanc() {
        return new TRetCancCTe.InfCanc();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TConsStatServ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "consStatServCte")
    public JAXBElement<TConsStatServ> createConsStatServCte(TConsStatServ value) {
        return new JAXBElement<TConsStatServ>(_ConsStatServCte_QNAME, TConsStatServ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "CTe")
    public JAXBElement<TCTe> createCTe(TCTe value) {
        return new JAXBElement<TCTe>(_CTe_QNAME, TCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProcCancCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "procCancCTe")
    public JAXBElement<TProcCancCTe> createProcCancCTe(TProcCancCTe value) {
        return new JAXBElement<TProcCancCTe>(_ProcCancCTe_QNAME, TProcCancCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TEnviCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "enviCTe")
    public JAXBElement<TEnviCTe> createEnviCTe(TEnviCTe value) {
        return new JAXBElement<TEnviCTe>(_EnviCTe_QNAME, TEnviCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetCancCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "retCancCTe")
    public JAXBElement<TRetCancCTe> createRetCancCTe(TRetCancCTe value) {
        return new JAXBElement<TRetCancCTe>(_RetCancCTe_QNAME, TRetCancCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetEnviCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "retEnviCte")
    public JAXBElement<TRetEnviCTe> createRetEnviCte(TRetEnviCTe value) {
        return new JAXBElement<TRetEnviCTe>(_RetEnviCte_QNAME, TRetEnviCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetConsStatServ }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "retConsStatServCte")
    public JAXBElement<TRetConsStatServ> createRetConsStatServCte(TRetConsStatServ value) {
        return new JAXBElement<TRetConsStatServ>(_RetConsStatServCte_QNAME, TRetConsStatServ.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetInutCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "retInutCTe")
    public JAXBElement<TRetInutCTe> createRetInutCTe(TRetInutCTe value) {
        return new JAXBElement<TRetInutCTe>(_RetInutCTe_QNAME, TRetInutCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TInutCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "inutCTe")
    public JAXBElement<TInutCTe> createInutCTe(TInutCTe value) {
        return new JAXBElement<TInutCTe>(_InutCTe_QNAME, TInutCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetConsSitCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "retConsSitCTe")
    public JAXBElement<TRetConsSitCTe> createRetConsSitCTe(TRetConsSitCTe value) {
        return new JAXBElement<TRetConsSitCTe>(_RetConsSitCTe_QNAME, TRetConsSitCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProcInutCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "procInutCTe")
    public JAXBElement<TProcInutCTe> createProcInutCTe(TProcInutCTe value) {
        return new JAXBElement<TProcInutCTe>(_ProcInutCTe_QNAME, TProcInutCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TCancCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "cancCTe")
    public JAXBElement<TCancCTe> createCancCTe(TCancCTe value) {
        return new JAXBElement<TCancCTe>(_CancCTe_QNAME, TCancCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRetConsReciCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "retConsReciCTe")
    public JAXBElement<TRetConsReciCTe> createRetConsReciCTe(TRetConsReciCTe value) {
        return new JAXBElement<TRetConsReciCTe>(_RetConsReciCTe_QNAME, TRetConsReciCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TConsReciCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "consReciCTe")
    public JAXBElement<TConsReciCTe> createConsReciCTe(TConsReciCTe value) {
        return new JAXBElement<TConsReciCTe>(_ConsReciCTe_QNAME, TConsReciCTe.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TConsSitCTe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.portalfiscal.inf.br/cte", name = "consSitCTe")
    public JAXBElement<TConsSitCTe> createConsSitCTe(TConsSitCTe value) {
        return new JAXBElement<TConsSitCTe>(_ConsSitCTe_QNAME, TConsSitCTe.class, null, value);
    }

}
